FLUSH PRIVILEGES;

SET @userList = NULL;
SELECT GROUP_CONCAT('\'',user, '\'@\'', host, '\'') INTO @userList FROM mysql.user WHERE user = '$MARIA_DB_USERNAME';
SET @userList = CONCAT('DROP USER ', @userList);
PREPARE stmtUsers FROM @userList;
EXECUTE stmtUsers;
DEALLOCATE PREPARE stmtUsers;

GRANT ALL PRIVILEGES ON *.* TO '$MARIA_DB_USERNAME'@'127.0.0.1' IDENTIFIED BY '$MARIA_DB_PASSWORD';
GRANT ALL PRIVILEGES ON *.* TO '$MARIA_DB_USERNAME'@'localhost' IDENTIFIED BY '$MARIA_DB_PASSWORD';
GRANT ALL PRIVILEGES ON *.* TO '$MARIA_DB_USERNAME'@'::1' IDENTIFIED BY '$MARIA_DB_PASSWORD';

FLUSH PRIVILEGES;

